baseURL: 'https://finan.club/'
languageCode: 'en-us'
title: 'FinanClub'
theme: 'hugo-theme-financlub'
hasCJKLanguage: true
taxonomies:
  tags: 'tags'
  category: 'categories'
  social: 'social'
  author: 'author'
params:
  adsensePubId: 7398757278741889
  adsenseUnitId: 7456114770
  profiles:
    frank-lin: The only human in this team