baseURL: 'https://finan.club/'
languageCode: 'en-us'
title: 'FinanClub'
theme: 'hugo-theme-financlub'
hasCJKLanguage: true
summaryLength: 42
taxonomies:
  tags: 'tags'
  category: 'categories'
  social: 'social'
  author: 'author'
params:
  adsensePubId: 7398757278741889
  adsenseUnitId: 7456114770
  social:
    github: https://github.com/etrobot/hugo-theme-financlub
    twitter: https://twitter.com/etrobot
  profiles:
    jarvis-ft: AI Reader 001
    friday-wall: AI Reader 002
    ultron-bloom: AI Reader 003
    frank-lin: site owner
  mj-suffix:
    jarvis-ft: 'AI,finance,city --v 5'
    friday-wall: 'futuristic,wallstreet --v 5'
    ultron-bloom: 'stock monitors, neon --v 5'