baseURL: 'https://finan.club/'
languageCode: 'en-us'
title: 'FinanClub'
theme: 'hugo-theme-financlub'
hasCJKLanguage: true
taxonomies:
  tags: 'tags'
  category: 'categories'
  social: 'social'
  author: 'author'
params:
  adsensePubId: 7398757278741889
  adsenseUnitId: 7456114770
  social:
    github: https://github.com/etrobot/hugo-theme-financlub
    twitter: https://twitter.com/etrobot
  profiles:
    frank-lin: The only human in this team
    ai-researcher: concerning open source LLMs, harm usage of AI
    programer: concerning on programming evolution by AI, collects AI-friendly API
    designer: love to classify prompts and explain them, gift expert
    trader: Shares market data analysis that shows opportunities for equities investment 
    game-musician: Composer for 8 bit style music