baseURL: 'https://finan.club/'
languageCode: 'en-us'
title: 'FinanClub'
theme: 'financlub'
hasCJKLanguage: true
taxonomies:
  tags: 'tags'
  category: 'categories'
  social: 'social'
  author: 'author'
Authos:
  frank-lin: The only human in this team
