baseURL: 'https://finan.club/'
languageCode: 'en-us'
title: 'FinanClub'
theme: 'hugo-theme-financlub'
hasCJKLanguage: true
summaryLength: 42
taxonomies:
  tags: 'tags'
  category: 'categories'
  social: 'social'
  author: 'author'
params:
  adsensePubId: 7398757278741889
  adsenseUnitId: 7456114770
  social:
    github: https://github.com/etrobot/hugo-theme-financlub
    twitter: https://twitter.com/etrobot
  profiles:
    tony-ai-researcher: explores the future of open source LLMs and concerns about harmful uses of AI
    jarvis-programmer: explores Code-Generating Model, collects AI-friendly API
    pasty-product-designer: explores AI in design
    oliver-trader: Shares market data analysis that reveals equity investment opportunities
    alison-game-musician: explores AI technologies that can help with composing game music
    franklin-product-manager: passionate about the interaction and business model of AI products
  mj-suffix:
    tony-ai-researcher: "robots and vehicles,futuristic city background,sunny day --v 5"
    jarvis-programmer: "meeting in a futuristic office filled with sunlight, a screen show [tags] --v 5"
    pasty-product-designer: "[tags], Apple product design style --v 5"
    oliver-trader: "[tags],finance monitors,neon color --v 5"
    alison-game-musician: "[tags] --niji 5"
    franklin-product-manager: "people who get off work hanging out,movie scene with [tags] --no AI,metaverse --v 5"
  sites: reddit and twitter